# Test against the latest version of this Node.js version
environment:
  nodejs_version: "10"

# Install scripts. (runs after repo cloning)
install:
  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node $env:nodejs_version
  # install modules
  - yarn
  - yarn run vscode:prepublish

test_script:
  - yarn test --silent

# Don't actually build.
build: off