language: node_js
node_js:
  - 'stable'

os:
  - osx
  - linux
  - windows

branches:
  only:
  - master

before_install:
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
      sh -e /etc/init.d/xvfb start;
      sleep 3;
    fi

install:
  - yarn remove typescript --no-lockfile
  - yarn remove tslint --no-lockfile
  - yarn
  - yarn run vscode:prepublish

script:
  - yarn test --silent

cache:
  yarn: true

  git:
    depth: 1